--[[ 	To add a frame to this list, use this format and insert the line:
 	(you will need to reload the UI to see your changes)
	{ "XML Frame Name", "Text Displayed in GUI" },
	"Separator" is used as a "Frame Name" for text only fields. ]]

MoveAnything_PredefinedCustomFrameList = {
	{ "Separator", " " },
	{ "Separator", "**** Diiv's Skins ****" },
	{ "Separator", "** Horizontal Trays **" },
	{ "DiivSkins_hbar1", "Horizontal Tray 1" },
	{ "DiivSkins_hbar2", "Horizontal Tray 2" },
	{ "DiivSkins_hbar3", "Horizontal Tray 3" },
	{ "DiivSkins_hbar4", "Horizontal Tray 4" },
	{ "DiivSkins_hbar5", "Horizontal Tray 5" },
	{ "DiivSkins_hbar6", "Horizontal Tray 6" },
	{ "DiivSkins_hbar7", "Horizontal Tray 7" },
	{ "DiivSkins_hbar8", "Horizontal Tray 8" },
	{ "DiivSkins_hbar9", "Horizontal Tray 9" },
	{ "DiivSkins_hbar10", "Horizontal Tray 10" },
	{ "Separator", "** Vertical Trays **" },
	{ "DiivSkins_vbar1", "Vertical Tray 1" },
	{ "DiivSkins_vbar2", "Vertical Tray 2" },
	{ "DiivSkins_vbar3", "Vertical Tray 3" },
	{ "DiivSkins_vbar4", "Vertical Tray 4" },
	{ "DiivSkins_vbar5", "Vertical Tray 5" },
	{ "DiivSkins_vbar6", "Vertical Tray 6" },
	{ "DiivSkins_vbar7", "Vertical Tray 7" },
	{ "DiivSkins_vbar8", "Vertical Tray 8" },
	{ "DiivSkins_vbar9", "Vertical Tray 9" },
	{ "DiivSkins_vbar10", "Vertical Tray 10" },
	{ "Separator", "** Endcaps **" },
	{ "DiivSkins_endcap1", "End Cap 1" },
	{ "DiivSkins_endcap2", "End Cap 2" },
	{ "DiivSkins_endcap3", "End Cap 3" },
	{ "DiivSkins_endcap4", "End Cap 4" },
	{ "DiivSkins_endcap5", "End Cap 5" },
	{ "DiivSkins_endcap6", "End Cap 6" },
	{ "DiivSkins_endcap7", "End Cap 7" },
	{ "DiivSkins_endcap8", "End Cap 8" },
	{ "DiivSkins_endcap9", "End Cap 9" },
	{ "DiivSkins_endcap10", "End Cap 10" },
	{ "Separator", "** Miscellaneous Bits **" },
	{ "DiivSkins_miscbit1", "Misc. Bit 1" },
	{ "DiivSkins_miscbit2", "Misc. Bit 2" },
	{ "DiivSkins_miscbit3", "Misc. Bit 3" },
	{ "DiivSkins_miscbit4", "Misc. Bit 4" },
	{ "DiivSkins_miscbit5", "Misc. Bit 5" },
	{ "DiivSkins_miscbit6", "Misc. Bit 6" },
	{ "DiivSkins_miscbit7", "Misc. Bit 7" },
	{ "DiivSkins_miscbit8", "Misc. Bit 8" },
	{ "DiivSkins_miscbit9", "Misc. Bit 9" },
	{ "DiivSkins_miscbit10", "Misc. Bit 10" },
	{ "Separator", " " },
	{ "Separator", "**** Diiv's MoveAnything! Skins ****" },
	{ "Separator", "** Action Button Frames **" },
	{ "DS_actionbar", "skin for Action Buttons (Horizontal)" },
	{ "DS_actionbar_V", "skin for Action Buttons (Vertical)" },
	{ "Separator", "** Bag and Micro Buttons **"},
	{ "DS_bagbuttons", "skin for Bag Buttons (Horizontal)" },
	{ "DS_bagbuttons_V", "skin for Bag Buttons (Vertical)" },
	{ "DS_microbuttons", "skin for Micro Buttons (Horizontal)" },
	{ "DS_microbuttons_V", "skin for Micro Buttons (Vertical)" },
	{ "Separator", "** individual Micro Buttons **"},
	{ "CharacterMicroButton", "character button" },
	{ "SpellbookMicroButton", "spellbook button" },
	{ "TalentMicroButton", "talent button" },
	{ "QuestLogMicroButton", "questlog button" },
	{ "SocialsMicroButton", "social window button" },
	{ "WorldMapMicroButton", "world map button" },
	{ "MainMenuMicroButton", "main menu button" },
	{ "HelpMicroButton", "help button" },
	{ "Separator", "** Miscellaneous MoveAnything! bits**"},
	{ "DS_expbar", "skin for Experience Bar" },
	{ "DS_performancebar", "skin for Lag Meter" },

--[[ still in development
	{ "Separator", " " },
	{ "Separator", "**** Diiv's optional Plugins ****" },
	{ "DiivBagsFrame", "DiivBags Button" },	]]

	{ "Separator", " " },
	{ "Separator", "**** Your own custom movable windows ****" },
	{ "AllInOneInventoryFrame", "All-In-One-Inventory" },
	{ "AtlasFrame", "Atlas instance map viewer" },
	{ "ClassVFrame", "Class Viewer Icon" },
	{ "Gypsy_Button", "Gypsy Options Button" },
	{ "Gypsy_LockButton", "Gypsy Capsule Lock Button" },
	{ "ItemBuffFrame", "Telo's Item Buff" },
	{ "RogueHelperFrame", "Rougue Helper Display" },
	{ "TotemTimersFrame", "Totem Timer's Display" },
	{ "WeaponButtonsFrame", "Weapon Buttons Display" },
	{ "Separator", " " },
	{ "FBEventEditorFrame", "Flexbar events editor" },
	{ "FBScriptsEditorFrame", "Flexbar scripts editor" },

--[[	if you are adding your own "EGGS" 
	uncomment and make adjustments below 	]]
	
--	{ "Separator", "**** Your own custom image frames ****" },
--	{ "DiivSkins_SampleFrame", "description of your Frame" },
}